[versions]
agp = "8.7.3"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
firebase = "32.2.0"
google-services = "4.3.10"
glide = "4.12.0"
gson = "2.10.1"
eventbus = "3.3.1"
exoplayer = "2.19.1"
flowlayout = "1.1.3"
paypal = "2.16.0"
zxing = "3.3.3"
material-dialogs = "3.3.0"
circleimageview = "3.1.0"
circleindicator = "2.1.6"
[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-database = { module = "com.google.firebase:firebase-database-ktx", version.ref = "firebase" }
firebase-auth = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebase" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
flowlayout = { module = "com.nex3z:flow-layout", version.ref = "flowlayout" }
paypal = { module = "com.paypal.sdk:paypal-android-sdk", version.ref = "paypal" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }
zxing-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxing" }
material-dialogs = { module = "com.afollestad.material-dialogs:core", version.ref = "material-dialogs" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
circleindicator = { module = "me.relex:circleindicator", version.ref = "circleindicator" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }

